name: Deploy Lambda Function

on:
  push:
    paths:
      - "src/**"

    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install zip tool
        uses: montudor/action-zip@v1
      - name: Create zip file for lambda Function
        run: cd src && zip -r code.zip .
      - name: AWS CLI v2
        uses: imehedi/actions-awscli-v2@v1.0.19
        with:
          args: "lambda update-function-code \
          --function-name arn:aws:lambda:us-west-2:532284260787:function:Test_scraper_CICD_01 \
          --zip-file fileb://src/code.zip"

        env:
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: "us-west-2"
